source 'https://rubygems.org/' do
  gem 'test-kitchen', '~> 2.5.0'
  gem 'kitchen-terraform', '~> 5.3.0'
  gem 'kitchen-verifier-awspec', '~> 0.2.0'
  gem 'awspec', git: 'https://github.com/7Factor/awspec' # @todo - revert back to original repo when our change is merged in
  gem 'hcl-checker'
end
